#ifndef MEIDAPLAYERVIEW_GLOBAL_H
#define MEIDAPLAYERVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MEIDAPLAYERVIEW_LIB
# define MEIDAPLAYERVIEW_EXPORT Q_DECL_EXPORT
#else
# define MEIDAPLAYERVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // MEIDAPLAYERVIEW_GLOBAL_H
